### ISSUE TITLE
Fetching meteofrance data gives many "Connection reset by peer" errors

### ISSUE THREAD

**Issue by drmrbrewer** [open-meteo/open-meteo#871]
When using self-hosted to download data from meteofrance (e.g. `openmeteo-api download-meteofrance arpege_europe`), recently there seem to be lots of download errors.  Several files seem to download OK, but lots (possibly most) seem to get an error. 

For example see the following sequence in the logs:

	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=HIGH_CLOUD_COVER__GROUND_OR_WATER_SURFACE___2024-06-21T18.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=time(18000)&format=application%2Fwmo-grib
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=MEDIUM_CLOUD_COVER__GROUND_OR_WATER_SURFACE___2024-06-21T18.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=time(18000)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 0 seconds, (0 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=PRESSURE__MEAN_SEA_LEVEL___2024-06-21T18.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=time(18000)&format=application%2Fwmo-grib
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=RELATIVE_HUMIDITY__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-21T18.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(2)&subset=time(18000)&format=application%2Fwmo-grib
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=V_COMPONENT_OF_WIND__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-21T18.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(10)&subset=time(18000)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 0 seconds, (0 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'

Sometimes it really seems to get stuck:

	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=HIGH_CLOUD_COVER__GROUND_OR_WATER_SURFACE___2024-06-21T18.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=time(28800)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 0 seconds, (0 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=MEDIUM_CLOUD_COVER__GROUND_OR_WATER_SURFACE___2024-06-21T18.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=time(28800)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 0 seconds, (0 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=PRESSURE__MEAN_SEA_LEVEL___2024-06-21T18.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=time(28800)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 0 seconds, (0 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=RELATIVE_HUMIDITY__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-21T18.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(2)&subset=time(28800)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 0 seconds, (0 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=V_COMPONENT_OF_WIND__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-21T18.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(10)&subset=time(28800)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 0 seconds, (0 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=U_COMPONENT_OF_WIND__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-21T18.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(10)&subset=time(28800)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 0 seconds, (0 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=V_COMPONENT_OF_WIND__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-21T18.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(20)&subset=time(28800)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 0 seconds, (0 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=U_COMPONENT_OF_WIND__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-21T18.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(20)&subset=time(28800)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 0 seconds, (0 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=V_COMPONENT_OF_WIND__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-21T18.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(50)&subset=time(28800)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 0 seconds, (0 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=U_COMPONENT_OF_WIND__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-21T18.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(50)&subset=time(28800)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 0 seconds, (0 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=V_COMPONENT_OF_WIND__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-21T18.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(100)&subset=time(28800)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 0 seconds, (0 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=U_COMPONENT_OF_WIND__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-21T18.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(100)&subset=time(28800)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 0 seconds, (0 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=V_COMPONENT_OF_WIND__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-21T18.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(150)&subset=time(28800)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 0 seconds, (0 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=U_COMPONENT_OF_WIND__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-21T18.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(150)&subset=time(28800)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 0 seconds, (0 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'

Any ideas?

I did wonder if it was some form of rate limiting, because there seems to be a limit of 50 request/min for each model... and the requests from the openmeteo api seem like they could exceed that (if multiple model data are being downloaded simultaneously)?

![image](https://github.com/open-meteo/open-meteo/assets/9009792/44668e72-b519-479a-bfb4-99f36e4bb473)

**Comment by patrick-zippenfenig** [comment]
Hi,
I am observing the same issue and already tried a couple of workarounds. E.g. Using new connections for every call instead of keep-alive, etc. Nothing seems to work. Sometimes even the first HTTP call will immediately get a `Connection reset by peer` error.
MeteoFrance also re-introduced the old SP1,2,3... GRIB packages. I am working on a downloader right now, but downloading larger GRIB files seems to be even worse with the new MeteoFrance API (stalled transfers, etc)...

**Comment by drmrbrewer** [comment]
OK that's frustrating.  How responsive are MF if/when you reach out for help?

**Comment by patrick-zippenfenig** [comment]
I do not have any contacts at MF and I never received a response when writing an email

**Comment by drmrbrewer** [comment]
It doesn't seem like they are making progress in the right direction.

**Comment by patrick-zippenfenig** [comment]
If the goal is to make it as hard as possible to use open-data, they are right on track :) They also removed solar radiation from the API. However the field is still in the GRIB package files.

**Comment by patrick-zippenfenig** [comment]
Note: The MeteoFrance API to fetch individual GRIB records is now entirely broken and returns Error 500 on every request. The newer API to fetch GRIB packages (SP1,SP2,...) still works. I am trying to merge an updated downloader in the next hours: https://github.com/open-meteo/open-meteo/pull/870

```xml
<?xml version="1.0" encoding="UTF-8"?>
  <mw:fault xmlns:mw="http://metwork-framework.org/">
    <mw:code>868400</mw:code>
    <mw:message>Synopsis backend error</mw:message>
    <mw:description>
      <ns0:ExceptionReport xmlns:ns0="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsAll.xsd">
        <ns0:Exception exceptionCode="NoApplicableCode" locator="">
          <ns0:ExceptionText>InternalServerError</ns0:ExceptionText>
        </ns0:Exception>
      </ns0:ExceptionReport>
    </mw:description>
  </mw:fault>
```

**Comment by drmrbrewer** [comment]
Looking at recent logs, I'm seeing a whole bunch of different errors: 400, 500, 104... and eventually it crashes:

	[ INFO ] Downloading domain 'arpege_world' run '2024-06-23T00:00'
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-025-GLOBE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=TEMPERATURE__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-23T00.00.00Z&subset=long(-180,180)&subset=lat(-90,90)&subset=height(2)&subset=time(0)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 0 seconds, (0 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Download failed, retry every 5 seconds, (1 minutes elapsed, curl error 'downloadFailed(code: 400 Bad Request) [CurlError]'
	[ INFO ] Download failed, retry every 5 seconds, (2 minutes elapsed, curl error 'downloadFailed(code: 400 Bad Request) [CurlError]'
	[ INFO ] Download failed, retry every 5 seconds, (3 minutes elapsed, curl error 'downloadFailed(code: 400 Bad Request) [CurlError]'
	[ INFO ] Download failed, retry every 5 seconds, (4 minutes elapsed, curl error 'downloadFailed(code: 400 Bad Request) [CurlError]'
	[ INFO ] Download failed, retry every 5 seconds, (5 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Download failed, retry every 5 seconds, (6 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Download failed, retry every 5 seconds, (7 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Download failed, retry every 5 seconds, (8 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Download failed, retry every 5 seconds, (9 minutes elapsed, curl error 'downloadFailed(code: 400 Bad Request) [CurlError]'
	[ INFO ] Download failed, retry every 5 seconds, (10 minutes elapsed, curl error 'downloadFailed(code: 400 Bad Request) [CurlError]'
	[ INFO ] Download failed, retry every 5 seconds, (11 minutes elapsed, curl error 'downloadFailed(code: 400 Bad Request) [CurlError]'
	[ INFO ] Download failed, retry every 5 seconds, (12 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Download failed, retry every 5 seconds, (13 minutes elapsed, curl error 'downloadFailed(code: 400 Bad Request) [CurlError]'

	[...]

	[ INFO ] Download failed, retry every 5 seconds, (158 minutes elapsed, curl error 'downloadFailed(code: 400 Bad Request) [CurlError]'
	[ INFO ] Download failed, retry every 5 seconds, (159 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Download failed, retry every 5 seconds, (161 minutes elapsed, curl error 'downloadFailed(code: 500 Internal Server Error) [CurlError]'
	[ INFO ] Download failed, retry every 5 seconds, (162 minutes elapsed, curl error 'downloadFailed(code: 500 Internal Server Error) [CurlError]'
	[ INFO ] Download failed, retry every 5 seconds, (163 minutes elapsed, curl error 'downloadFailed(code: 400 Bad Request) [CurlError]'
	[ INFO ] Download failed, retry every 5 seconds, (164 minutes elapsed, curl error 'downloadFailed(code: 400 Bad Request) [CurlError]'

	[...]

	[ INFO ] Download failed, retry every 5 seconds, (232 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Download failed, retry every 5 seconds, (233 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Download failed, retry every 5 seconds, (234 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Download failed, retry every 5 seconds, (235 minutes elapsed, curl error 'downloadFailed(code: 400 Bad Request) [CurlError]'
	[ INFO ] Download failed, retry every 5 seconds, (236 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Download failed, retry every 5 seconds, (237 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Download failed, retry every 5 seconds, (238 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'

	[...]

	[ INFO ] Download failed, retry every 5 seconds, (327 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Download failed, retry every 5 seconds, (328 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Download failed, retry every 5 seconds, (329 minutes elapsed, curl error 'downloadFailed(code: 400 Bad Request) [CurlError]'
	[ ERROR ] Deadline reached. Last Error read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]
	[ WARNING ] App.CurlError.timeoutReached Swift/ErrorType.swift:200: Fatal error: Error raised at top level: App.CurlError.timeoutReached

	*** Signal 5: Backtracing from 0xffff8dc2dd70... done ***

	*** Program crashed: System trap at 0x0000ffff8dc2dd70 ***

	Thread 0 "NIO-SGLTN-0-#9" crashed:

	0      0x0000ffff8dc2dd70 _assertionFailure(_:_:file:line:flags:) + 256 in libswiftCore.so
	1 [ra] 0x0000ffff8dc91010 swift_errorInMain + 487 in libswiftCore.so
	2 [ra] 0x0000ffff8da956d8 swift::runJobInEstablishedExecutorContext(swift::Job*) + 407 in libswift_Concurrency.
	so
	3 [ra] 0x0000ffff8da96000 swift_job_run + 95 in libswift_Concurrency.so
	4 [ra] 0x0000ffff8d7ae1ec _dispatch_lane_serial_drain + 427 in libdispatch.so
	5 [ra] 0x0000ffff8d7aee20 _dispatch_lane_invoke + 751 in libdispatch.so
	6 [ra] 0x0000ffff8d7b5948 _dispatch_worker_thread + 439 in libdispatch.so
	7 [ra] 0x0000ffff8ca4d5c8 <unknown> in libc.so.6


Looks like it's in freefall.

**Comment by patrick-zippenfenig** [comment]
I have got a first version ready that downloads packaged GRIB files from the revised MF API. It is now downloading previous runs and backfills data. There were plenty of issues with data deaveraging, stalled transfers etc, that I will wait a day or two before merging.

**Comment by patrick-zippenfenig** [comment]
Still some bugs remaining in the global ARPEGE model

![Screenshot 2024-06-23 at 18 10 08](https://github.com/open-meteo/open-meteo/assets/11670456/ea8c08d0-75b5-459a-b62e-94efd371acdd)

**Comment by libertykite** [comment]
Maybe it's a good solution to take the data from Meteofrance on amazon S3?
Nicolas Baldek from Meteo parapente did a good job on this side

[](https://mf-models-on-aws.org/#arome-france-hd/)

**Comment by patrick-zippenfenig** [comment]
This distribution is a bit outdated. It lacks the 0.25° ARPEGE WORLD model, AROME-PI models with 15 minutes data, some variables and not the full forecast horizon.

**Comment by patrick-zippenfenig** [comment]
Issues are now fixed. I am now merging the additional downloader to process GRIB packages directly.

In the meantime, someone at MeteoFrance fixed the API and regular downloads are working again including AROME-PI with 15 minutely values.

![Screenshot 2024-06-24 at 11 12 59](https://github.com/open-meteo/open-meteo/assets/11670456/e48ae83a-2b0b-43cb-ad6c-1fd42401994c)

**Comment by drmrbrewer** [comment]
> now merging the additional downloader to process GRIB packages directly

This will be an additional downloader or a replacement downloader?  Will it still be accessed via the same command e.g. `openmeteo-api download-meteofrance arpege_europe`?

With the existing downloader, I'm still getting some `104` errors (see below).  But I'm also getting some `429 Too Many Requests` errors, which I don't think I've seen before.  Could the downloader be configured to try and stick to the request limit imposed by MF, or is it easiest just to try as often as possible and let the rate limiter on MF's side do it's stuff?

	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=U_COMPONENT_OF_WIND__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-24T06.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(200)&subset=time(25200)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 0 seconds, (0 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=TEMPERATURE__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-24T06.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(20)&subset=time(25200)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 0 seconds, (0 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=TEMPERATURE__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-24T06.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(50)&subset=time(25200)&format=application%2Fwmo-grib
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=TEMPERATURE__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-24T06.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(100)&subset=time(25200)&format=application%2Fwmo-grib
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=TEMPERATURE__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-24T06.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(150)&subset=time(25200)&format=application%2Fwmo-grib
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=TEMPERATURE__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-24T06.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(200)&subset=time(25200)&format=application%2Fwmo-grib
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=TOTAL_PRECIPITATION__GROUND_OR_WATER_SURFACE___2024-06-24T06.00.00Z_PT1H&subset=lat(20,72)&subset=long(-32,42)&subset=time(25200)&format=application%2Fwmo-grib
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=TOTAL_SNOW_PRECIPITATION__GROUND_OR_WATER_SURFACE___2024-06-24T06.00.00Z_PT1H&subset=lat(20,72)&subset=long(-32,42)&subset=time(25200)&format=application%2Fwmo-grib
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=WIND_SPEED_GUST__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-24T06.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(10)&subset=time(25200)&format=application%2Fwmo-grib
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=CONVECTIVE_AVAILABLE_POTENTIAL_ENERGY__GROUND_OR_WATER_SURFACE___2024-06-24T06.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=time(25200)&format=application%2Fwmo-grib
	[ INFO ] Downloading file https://public-api.meteofrance.fr/public/arpege/1.0/wcs/MF-NWP-GLOBAL-ARPEGE-01-EUROPE-WCS/GetCoverage?service=WCS&version=2.0.1&coverageid=TEMPERATURE__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND___2024-06-24T06.00.00Z&subset=lat(20,72)&subset=long(-32,42)&subset=height(2)&subset=time(28800)&format=application%2Fwmo-grib
	[ INFO ] Download failed, retry every 5 seconds, (0 minutes elapsed, curl error 'downloadFailed(code: 429 Too Many Requests) [CurlError]'
	[ INFO ] Download failed, retry every 5 seconds, (1 minutes elapsed, curl error 'read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [IOError]'

**Comment by patrick-zippenfenig** [comment]
`openmeteo-api download-meteofrance arpege_europe --use-grib-packages` enables the alternative SP download. If have not yet published any docker images. If you want to try it now, you have to build from source

The number of retry errors should be the same. On 429 errors, the downloader retries every 5 seconds. This seems reasonable. It would be fairly difficult to perform rate limiting on client side

**Comment by drmrbrewer** [comment]
OK thanks.  My understanding from what you said is that someone at MF has fixed the existing API, so that you're no longer seeing `Connection reset by peer (errno: 104)`?  I'm still seeing plenty of these... though perhaps fewer than before.

**Comment by patrick-zippenfenig** [comment]
They fixed only fixed the issue that the API was not returned any data at all. I do not think there will be any change regarding the `Connection reset by peer (errno: 104)` errors.

**Comment by drmrbrewer** [comment]
> `openmeteo-api download-meteofrance arpege_europe --use-grib-packages` enables the alternative SP download. 

And the processed output is in the same format and in the same places?  e.g. `./data/meteofrance_arpege_europe/pressure_msl/chunk_2568.om`?

**Comment by patrick-zippenfenig** [comment]
Yes
